//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class InputUIEventTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(InputUIEventType));
		L.RegVar("Click", get_Click, null);
		L.RegVar("Scroll", get_Scroll, null);
		L.RegVar("PressDown", get_PressDown, null);
		L.RegVar("PressUp", get_PressUp, null);
		L.RegVar("LongPress", get_LongPress, null);
		L.RegVar("BeginDrag", get_BeginDrag, null);
		L.RegVar("Drag", get_Drag, null);
		L.RegVar("EndDrag", get_EndDrag, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Click(IntPtr L)
	{
		ToLua.Push(L, InputUIEventType.Click);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Scroll(IntPtr L)
	{
		ToLua.Push(L, InputUIEventType.Scroll);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PressDown(IntPtr L)
	{
		ToLua.Push(L, InputUIEventType.PressDown);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PressUp(IntPtr L)
	{
		ToLua.Push(L, InputUIEventType.PressUp);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LongPress(IntPtr L)
	{
		ToLua.Push(L, InputUIEventType.LongPress);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BeginDrag(IntPtr L)
	{
		ToLua.Push(L, InputUIEventType.BeginDrag);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Drag(IntPtr L)
	{
		ToLua.Push(L, InputUIEventType.Drag);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EndDrag(IntPtr L)
	{
		ToLua.Push(L, InputUIEventType.EndDrag);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		InputUIEventType o = (InputUIEventType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

